version: '3'
services:
  rmqnamesrv:
    image: apache/rocketmq:4.9.4
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh "mqnamesrv"
    restart: unless-stopped
    networks:
      - elk-network

  rmqbroker:
    image: apache/rocketmq:4.9.4
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
    command: /bin/sh -c "export PATH=$PATH:/home/rocketmq/rocketmq-4.9.4/bin && sh mqbroker -c /home/rocketmq/rocketmq-4.9.4/conf/broker.conf"
    depends_on:
      - rmqnamesrv
    restart: unless-stopped
    networks:
      - elk-network
      
networks:
  elk-network:
    external: true